apiVersion: v1
kind: Service
metadata:
  name: istioapp-service
  labels:
    app: istioapp
spec:
  selector:
    app: istioapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
